name: Package Website

on:
  push:
    branches:
      - master

env:
  PACKAGE_PREFIX: 2020.1.1
  OCTOPUS_PROJECT_NAME: io
  OCTOPUS_SPACE_NAME: Default
  OCTOPUS_ENVIRONMENT_NAME: Production
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Yarn build
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command

      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: audit # will run `yarn audit` command

      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build # will run `yarn build` command
      #      - uses: borales/actions-yarn@v2.0.0
      #        with:
      #          cmd: test # will run `yarn test` command

      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/

      - name: Set version
        id: set-version
        run: echo "::set-env name=PACKAGE_VERSION::$PACKAGE_PREFIX.$GITHUB_RUN_NUMBER"

      - name: Install Octopus CLI
        run: |
          sudo apt update && sudo apt install --no-install-recommends gnupg curl ca-certificates apt-transport-https && \
          curl -sSfL https://apt.octopus.com/public.key | sudo apt-key add - && \
          sudo sh -c "echo deb https://apt.octopus.com/ stable main > /etc/apt/sources.list.d/octopus.com.list" && \
          sudo apt update && sudo apt install octopuscli

#       - name: Package and Push to Octopus
#         run: |
#           octo pack --id="MyApp.Web" --format="Zip" --version="$PACKAGE_VERSION" --basePath="./dist/" --outFolder="./packages" && \
#           octo push --package="./packages/MyApp.Web.$PACKAGE_VERSION.zip" --server="${{ secrets.OCTOPUS_SERVER }}" --apiKey="${{ secrets.OCTOPUS_APIKEY }}"

#       - name: Create and Deploy Release
#         run: octo create-release --project="$OCTOPUS_PROJECT_NAME" --packageVersion="$PACKAGE_VERSION" --releaseNumber="$PACKAGE_VERSION" --server="${{ secrets.OCTOPUS_SERVER }}" --apiKey="${{ secrets.OCTOPUS_APIKEY }}" --space="$OCTOPUS_SPACE_NAME" --deployTo="$OCTOPUS_ENVIRONMENT_NAME"
