name: Octopus Project

# env:
#   project: io
#   server: https://bartholomews.octopus.app

env:
  PACKAGE_PREFIX: 2020.1.1
  OCTOPUS_PROJECT_NAME: io
  OCTOPUS_SPACE_NAME: Default
  OCTOPUS_ENVIRONMENT_NAME: Production
  
on:
  push:
    branches: master
    
#   schedule:
#     - cron: '0 0 * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Yarn install
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install

#       - name: Yarn audit
#       - uses: borales/actions-yarn@v2.0.0
#         with:
#           cmd: audit
  
      - name: Yarn build
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: build
    
      - name: Prepare artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/

      - name: Set version
        id: set-version
        run: echo "::set-env name=PACKAGE_VERSION::$PACKAGE_PREFIX.$GITHUB_RUN_NUMBER"

      - name: Install Octopus Command-Line Interface
        run: sudo apt update && sudo apt install --no-install-recommends gnupg curl ca-certificates apt-transport-https &&
             curl -sSfL https://apt.octopus.com/public.key | sudo apt-key add - &&
             sudo sh -c "echo deb https://apt.octopus.com/ stable main > /etc/apt/sources.list.d/octopus.com.list" &&
             sudo apt update && sudo apt install octopuscli
             
      - name: Create Deployment Directory
        run: mkdir /tmp/deployments
             
#       - name: List Releases
#         run: octo list-deployments --project=${{ env.project }} --server=${{ secrets.OCTOPUS_SERVER }} --apiKey=${{ secrets.OCTOPUS_APIKEY }} >> /tmp/deployments/deployments.txt

#       - name: Azure Storage Action
#         uses: lauchacarro/Azure-Storage-Action@v1.1
#         with:
#           connection-string: ${{ secrets.StorageAccountConnectionString }}
#           folder: /tmp/deployments
#           blob-container-name: deployments

#       - name: Package and Push to Octopus
#         run: |
#           octo pack --id="dist" --format="Zip" --version="$PACKAGE_VERSION" --basePath="./dist/" --outFolder="./packages" && \
#           octo push --package="./packages/dist.${PACKAGE_VERSION}.zip" --server="${{ secrets.OCTOPUS_SERVER }}" --apiKey="${{ secrets.OCTOPUS_APIKEY }}"

      - name: Package and Push to Octopus
        run: |
          octo pack --id="dist" --format="Zip" --version="$PACKAGE_VERSION" --basePath="./dist/" --outFolder="./packages" && \
          echo ${PACKAGE_VERSION} && \
          ls packages && \
          octo push --package="./packages/dist.${PACKAGE_VERSION}.zip" --server="${{ secrets.OCTOPUS_SERVER }}" --apiKey="${{ secrets.OCTOPUS_APIKEY }}"
          
      - name: Create and Deploy Release
        run: octo create-release --project="$OCTOPUS_PROJECT_NAME" --packageVersion="$PACKAGE_VERSION" --releaseNumber="$PACKAGE_VERSION" --server="${{ secrets.OCTOPUS_SERVER }}" --apiKey="${{ secrets.OCTOPUS_APIKEY }}" --space="$OCTOPUS_SPACE_NAME" --deployTo="$OCTOPUS_ENVIRONMENT_NAME"
